name: BeaconLabsBW
version: '1.0.0'
main: org.bcnlab.beaconLabsBW.BeaconLabsBW
api-version: '1.21'
load: STARTUP
authors: [ Vincent Wackler ]
website: bcnlab.org
permissions:
  bedwars.admin:
    description: Gives access to all BedWars admin commands
    default: op
  bedwars.edit:
    description: Allows editing arenas
    default: op
  bedwars.create:
    description: Allows creating new arenas
    default: op
  bedwars.delete:
    description: Allows deleting arenas
    default: op
  bedwars.play:
    description: Allows playing BedWars
    default: true
commands:
  labsbw:
    description: 'Main BeaconLabsBW plugin command'
    usage: '/labsbw <subcommand>'
    aliases: [ labsbedwars, bw ]
    permission: bedwars.play
  forceteam:
    description: 'Force a player onto a specific team'
    usage: '/forceteam [player] <team>'
    permission: bedwars.admin
  forcemap:
    description: 'Change map of waiting lobby'
    usage: '/forcemap <arena>'
    permission: bedwars.admin
  forcestart:
    description: 'Reduce countdown to 3 seconds'
    usage: '/forcestart'
    permission: bedwars.admin
  mode:
    description: 'Change the game mode between normal and ultimates'
    usage: '/mode <normal|ultimates>'
    permission: bedwars.play
  shopnpc:
    description: 'Manage shop NPCs (villagers) for item shops and team upgrades'
    usage: '/shopnpc <place|remove|edit|list>'
    permission: bedwars.admin